import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { library, icon } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faInstagram } from '@fortawesome/free-brands-svg-icons';
import { faTwitter } from '@fortawesome/free-brands-svg-icons';

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/" />
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@100;400;500&family=Lalezar&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Heebo:wght@100;400;500&family=Lalezar&display=swap" rel="stylesheet"></link>
      </Head>
      <div className='awge-stars'></div>
      <div className="nav">
        <h2>HIDJI</h2>
      </div>
      <div className="videos">
        <iframe width="600" height="400" src="https://www.youtube.com/embed/0NzlbBmkM3E" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/Vx-SmmbzEAQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/zgLYhRVoL0g" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/PoK2m6Mu53A" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/xiVqKFDqxyg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/4LRJoKWgT9U" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/zpL3velgzmQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/FUQI-o02JYU" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/pM5XogpX1JA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/93M1QtYDtpU" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/Kbj2Zss-5GY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/BNzc6hG3yN4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/BnANUza_uXQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/X6SaVOLRcF4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/8Y4eFnLRIzI" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/LtlO4FVzXew" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/meXPbvp3ldg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/wcJVXg7gg4w" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/_JZqoGz0b6o" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/oCveByMXd_0" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/_eLryuBCO-M" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/wQ274umjhFY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/tt7gP_IW-1w" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <div className='socials'>
        <a href="https://www.instagram.com/hidjiworld/?hl=en" target="_blank"><FontAwesomeIcon icon={faInstagram} size="1x" /></a>
        <a href="https://twitter.com/hidjifilms?lang=en" target="_blank"><FontAwesomeIcon icon={faTwitter} size="1x" /></a>
      </div>
    </div>
  )
}
