import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { library, icon } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faInstagram } from '@fortawesome/free-brands-svg-icons';
import { faTwitter } from '@fortawesome/free-brands-svg-icons';

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/" />
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@100;400;500&family=Lalezar&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Heebo:wght@100;400;500&family=Lalezar&display=swap" rel="stylesheet"></link>
      </Head>
      <div className="nav">
        <h2>HIDJI WORLD</h2>
      </div>
      <div className="videos">
        <iframe width="600" height="400" src="https://www.youtube.com/embed/4LRJoKWgT9U" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/xiVqKFDqxyg" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/Vx-SmmbzEAQ" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/Y59uzXt-SaE" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/zgLYhRVoL0g" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/PoK2m6Mu53A" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/99U_-zcMs8E" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
        <iframe width="600" height="400" src="https://www.youtube.com/embed/0NzlbBmkM3E" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
        <iframe src="https://player.vimeo.com/video/730676635?h=b4b3e82696" width="600" height="400" frameBorder="0" allow="autoplay; fullscreen; picture-in-picture" allowFullScreen></iframe>
      </div>
      <div className='socials'>
        <a href="https://www.instagram.com/hidjiworld/?hl=en" target="_blank" rel="noreferrer"><FontAwesomeIcon icon={faInstagram} size="1x" /></a>
        <a href="https://twitter.com/hidjifilms?lang=en" target="_blank" rel="noreferrer"><FontAwesomeIcon icon={faTwitter} size="1x" /></a>
      </div>
    </div>
  )
}
